version: '3'
services:
  tests:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./tests:/tests"
      - "./screenshots:/screenshots"
      - "./node_modules:/node_modules"
      - "./package.json:/package.json"
      - "./package-lock.json:/package-lock.json"
      - "./dist:/crx"
